### ISSUE TITLE
SpaceCamPlugin.dll Doesn't Load Correctly

### ISSUE THREAD

**Issue by K4tniss** [Jimmacle/SE-SpaceCamPlugin#2]
Crash http://pastebin.com/vvPBWpfv was generated when I started SE with "-plugin SpaceCamPlugin.dll", 
never got farther than splash screen.

I would assume that it's related either to .net version or something weird, or you expected it might be something with url format.

**Comment by Jimmacle** [comment]
Determined to be a problem with how Windows handles DLLs downloaded from the internet. After the DLL is downloaded you need to right click on it, go to Properties, tick the "Unblock" checkbox, then click apply.
